// DO NOT EDIT THIS FILE - it is machine generated -- Template: Iterator.txt
package com.besaba.revonline.primitivecollections.iterables.iterators;

/**
 * @author Marco
 * @since 1.0
 */
public interface DoubleIterator {
    boolean hasNext();

    double next();
}
