// DO NOT EDIT THIS FILE - it is machine generated -- Template: Iterable.txt
package com.besaba.revonline.primitivecollections.iterables;

import com.besaba.revonline.primitivecollections.iterables.iterators.DoubleIterator;

/**
 * @author Marco
 * @since 1.0
 */
public interface DoubleIterable {
    DoubleIterator iterator();
}
